[theme]
primaryColor = "#1E49B6"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F7FE"
textColor = "#0B1330"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true

[browser]
gatherUsageStats = false
